from django.urls import path
from . import views 
from rest_framework_simplejwt.views import(
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    path('add/',views.add_employee,name='add_employee'),
    path('view/',views.view_employee,name='view_employee'),
    path('search/<int:Emp_Id>/',views.search_employee,name='search_employee'),
    path('update/<int:Emp_Id>/',views.update_employee,name='update_employee'),
    path('delete/<int:Emp_Id>/',views.delete_employee,name='delete_employee'),
    path('search-name/',views.search_name,name='search_name'),
    path('search-email/',views.search_email,name='search_email'),
    path('search-department/',views.search_department,name='search_department'),
    path('search-city/',views.search_city,name='search_city'),
    path('pagination/',views.pagination_employee,name='pagination_employee'),
    path('sort-ascending/',views.sort_ascending,name='sort_ascending'),
    path('sort-descending/',views.sort_descending,name='sort_descending'),
    path("recently-added/", views.recently_added, name="recently_added"),
    path('signup/',views.signup_employee,name='signup_employee'),
    path('login/',views.login_employee,name='login_employee'),
    path('logout/',views.logout_employee,name='logout_employee'),
    path('login-page/',views.login_page,name='login_page'),
    path('signup-page/',views.signup_page,name='signup_page'),
    path('dashboard/',views.dashboard,name="dashboard"),
     path('add_employee_page/',views.add_employee_page,name='add_employee_page'),
    path('view_employee_page/',views.view_employee_page,name='view_employee_page'),
    path('update_employee_page/<int:Emp_Id>/',views.update_employee_page,name='update_employee_page'),
    path("filter-status/", views.filter_status,name='filter_status'),
    path('user-dashboard/',views.user_dashboard,name='user_dashboard'),
    path("token/",TokenObtainPairView.as_view(),name="token_obtain_pair"),
    path("token/refresh/",TokenRefreshView.as_view(),name="token_refresh"),
    path("protected/", views.protected_route, name="protected_route"),
    path("profile/",views.view_profile,name="view_profile"),
    path("profile-page/", views.profile_page, name="profile_page"),
    path("user-profile-page/", views.user_profile_page, name="user_profile_page"),
    path("update-profile/",views.update_profile,name="update_profile"),
    path("update-profile-page/", views.update_profile_page, name="update_profile_page"),
    path("user-update-profile-page/",views.user_update_profile_page,name="user_update_profile_page"),
    path("change-password/",views.change_password,name="change_password"),
    path("change-password-page/",views.change_password_page,name="change_password_page"),
    path("user-change-password-page/",views.user_change_password_page,name="user_change_password_page"),
    path("forgot-password-page/", views.forgot_password_page, name="forgot_password_page"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("verify-otp-page/", views.verify_otp_page, name="verify_otp_page"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("reset-password-page/", views.reset_password_page, name="reset_password_page"),
]