# Generated by Django 5.2.6 on 2026-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=20)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
