# Generated by Django 5.2.6 on 2026-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_city_employee_password_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='City',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
