# Generated by Django 5.2.6 on 2026-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_city_employee_password_employee_user_and_more'),
    ]

    operations = [
       
        
        migrations.AddField(
            model_name='employee',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='profile_photos/default.png', null=True, upload_to='profile_photos/'),
        ),
       
    ]
