# Generated by Django 5.2.6 on 2026-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_city_employee_password_and_more'),
    ]

    operations = [
    
      
        migrations.AlterField(
            model_name='employee',
            name='Profile_Photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos/'),
        ),
      
    ]
