# Generated by Django 5.2.6 on 2026-08-10 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_admin_otp_admin_otp_created_at_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='UpdatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admin',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
       
        migrations.AddField(
            model_name='employee',
            name='CreatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
       
        migrations.AddField(
            model_name='employee',
            name='UpdatedBy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
       
    ]
