# Generated by Django 5.2.6 on 2026-08-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_city_employee_password_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User')], max_length=20, null=True),
        ),
       
      
       
    ]
