# Generated by Django 5.2.6 on 2026-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_city_employee_password_employee_status_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='employee',
            name='Role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=10),
        ),
    ]
