# Generated by Django 5.2.6 on 2026-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_city_employee_password_and_more'),
    ]

    operations = [
     
        migrations.AddField(
            model_name='employee',
            name='OTP',
            field=models.CharField(blank=True, default=True, max_length=6),
        ),
        migrations.AddField(
            model_name='employee',
            name='OTP_Created_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
    
    ]
