# Generated by Django 5.2.6 on 2026-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_city_employee_otp_employee_otp_created_at_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='employee',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
      
    ]
