# Generated by Django 5.2.6 on 2026-08-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_city_employee_password_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='OTP',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='admin',
            name='OTP_Created_At',
            field=models.DateTimeField(blank=True, null=True),
        ),
        
        
        migrations.AlterField(
            model_name='employee',
            name='OTP',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        
    ]
